spring:
  application:
    name: timesheet
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/timesheet?authSource=admin
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: Origin,Content-Type,Accept,Authorization
      allow-credentials: true
      max-age: 3600
